PlataformaEDUGEP/Controllers/TagsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.EntityFrameworkCore;
using PlataformaEDUGEP.Data;
using PlataformaEDUGEP.Models;

namespace PlataformaEDUGEP.Controllers
{
    /// <summary>
    /// Manages operations related to tags including creating, editing, deleting, and displaying tags.
    /// </summary>
    public class TagsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICompositeViewEngine _viewEngine;

        /// <summary>
        /// Initializes a new instance of the <see cref="TagsController"/> class.
        /// </summary>
        /// <param name="context">The database context used for tag management.</param>
        /// <param name="viewEngine">The view engine used to check for view existence.</param>
        public TagsController(ApplicationDbContext context, ICompositeViewEngine viewEngine)
        {
            _context = context;
            _viewEngine = viewEngine;
        }

        /// <summary>
        /// Displays the main view of tags, optionally filtered by a search string.
        /// </summary>
        /// <param name="search">The search term used to filter tags.</param>
        /// <returns>The view displaying a list of tags.</returns>
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string search)
        {
            var tags = _context.Tags.AsQueryable();

            if (!string.IsNullOrEmpty(search))
            {
                tags = tags.Where(t => EF.Functions.Like(t.Name, $"%{search}%"));  // Ensures case insensitivity depending on the database
            }

            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("_TagListPartial", await tags.ToListAsync());
            }

            return View(await tags.ToListAsync());
        }

        /// <summary>
        /// Displays details for a specific tag.
        /// </summary>
        /// <param name="id">The ID of the tag to display.</param>
        /// <returns>A view showing tag details or NotFound if the tag does not exist.</returns>
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            var tag = await GetTagById(id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        /// <summary>
        /// Provides a view to create a new tag.
        /// </summary>
        /// <returns>A view with a form to create a new tag.</returns>
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("_CreateTagPartial");
            }
            return View();
        }


        /// <summary>
        /// Handles the creation of a new tag.
        /// </summary>
        /// <param name="tag">The tag to create.</param>
        /// <returns>Redirects to the index if successful, otherwise returns the view with errors.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("TagId,Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        /// <summary>
        /// Provides a view to edit an existing tag.
        /// </summary>
        /// <param name="id">The ID of the tag to edit.</param>
        /// <returns>A view with a form to edit the tag or NotFound if the tag does not exist.</returns>
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags.FindAsync(id);
            if (tag == null)
            {
                return NotFound();
            }

            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("_EditTagPartial", tag); // Return partial view for AJAX requests
            }

            return View(tag);
        }


        /// <summary>
        /// Handles the update of an existing tag.
        /// </summary>
        /// <param name="id">The ID of the tag to update.</param>
        /// <param name="tag">The updated tag data.</param>
        /// <returns>Redirects to the index if successful, otherwise returns the view with errors.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("TagId,Name")] Tag tag)
        {
            if (!ModelState.IsValid)
            {
                return View(tag);
            }

            var existingTag = await GetTagById(id);
            if (existingTag == null)
            {
                return NotFound();
            }

            // Update the properties of the fetched tag
            existingTag.Name = tag.Name;

            try
            {
                _context.Update(existingTag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await TagExists(tag.TagId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
        }

        /// <summary>
        /// Displays a confirmation dialog for deleting a tag.
        /// </summary>
        /// <param name="id">The ID of the tag to delete.</param>
        /// <returns>A view asking for confirmation to delete the tag or NotFound if the tag does not exist.</returns>
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            var tag = await GetTagById(id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        /// <summary>
        /// Handles the deletion of a tag after confirmation.
        /// </summary>
        /// <param name="id">The ID of the tag to delete.</param>
        /// <returns>Redirects to the index if successful.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tag = await GetTagById(id);
            if (tag == null)
            {
                return NotFound();
            }

            _context.Tags.Remove(tag);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Retrieves a tag by its ID from the database.
        /// </summary>
        /// <param name="id">The ID of the tag to retrieve.</param>
        /// <returns>The tag if found; otherwise, null.</returns>
        private async Task<Tag> GetTagById(int? id)
        {
            if (id == null)
            {
                return null; // Return null immediately if the ID is null
            }

            return await _context.Tags.FindAsync(id);
        }

        /// <summary>
        /// Checks if a tag exists in the database.
        /// </summary>
        /// <param name="id">The ID of the tag to check.</param>
        /// <returns>True if the tag exists, false otherwise.</returns>
        private async Task<bool> TagExists(int id)
        {
            return await _context.Tags.AnyAsync(e => e.TagId == id);
        }

        /// <summary>
        /// Checks if a view with the specified name exists.
        /// </summary>
        /// <param name="name">The name of the view to check for existence.</param>
        /// <returns>A boolean value indicating whether the view exists (true) or not (false).</returns>
        private bool ViewExists(string name)
        {
            var result = _viewEngine.FindView(ControllerContext, name, false);
            return result.Success;
        }

    }
}

PlataformaEDUGEP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Plataforma EDUGEP</title>

    <!-- Favicon link -->
    <link rel="icon" href="~/images/folders.png" type="image/png">

    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@

    <link rel="stylesheet" href="~/css/mytheme.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PlataformaEDUGEP.styles.css" asp-append-version="true" />

    <!-- Include Select2 CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Plataforma EDUGEP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-d" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">Sobre</a>
                        </li>
                        <!-- Common link for all authenticated users -->
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Folders" asp-action="Index">Pastas</a>
                            </li>
                        }

                        <!-- Additional link for users authenticated as Admin -->
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Tags" asp-action="Index">Gestão de Etiquetas</a>
                            </li>
                        }

                        <!-- Additional links for users authenticated as Admin -->
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Auditoria
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Folders" asp-action="AuditLog">Pastas</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="StoredFiles" asp-action="FileAuditLog">Ficheiros</a></li>
                                </ul>
                            </li>
                        }


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: #303030;">
        <div class="container">
            <span style="color: white;">&copy; 2024 - Plataforma EDUGEP - </span>
            <a asp-area="" asp-controller="Home" asp-action="Privacy" style="color: whitesmoke">Privacidade</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Include Select2 JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

    <script>
        /// Important logic used in create modal form
        $(document).ready(function () {
            $('#createFolderModal').on('shown.bs.modal', function () {
                // Initialize Select2 for the dynamically loaded select element in the create form
                $('#tagSelect').select2({
                    dropdownParent: $('#createFolderModal'), // Ensures dropdown is appended to the modal
                    placeholder: "Selecionar etiquetas",
                    minimumInputLength: 2,
                    language: {
                        inputTooShort: function () {
                            return ""; // Returning empty string to hide the 'input too short' message
                        },
                        noResults: function () {
                            return "Nenhuma etiqueta associada";
                        },
                        searching: function () {
                            return "A procurar..."; // Custom message for searching
                        }
                    },
                    escapeMarkup: function (markup) {
                        return markup;
                    },
                    width: '100%', // Matches the Select2 input width to the parent container
                    ajax: {
                        url: '/Folders/GetTags', // Endpoint to fetch tags
                        dataType: 'json',
                        delay: 250,
                        data: function (params) {
                            return {
                                searchTerm: params.term // Search term for the query
                            };
                        },
                        processResults: function (data) {
                            return {
                                results: data.results // Data processing
                            };
                        },
                        cache: true
                    }
                }).on("select2:open", function (e) {
                    // Ensures the select element is visible when Select2 is opened
                    $(this).css('display', 'block');
                });
            });
        });

        // edit modal logic
        $(document).ready(function () {
            $('#editFolderModal').on('shown.bs.modal', function () {
                // Initialize Select2 for the dynamically loaded select element
                $('#editTagSelect').select2({
                    dropdownParent: $('#editFolderModal'), // Appends the dropdown to the modal
                    placeholder: "Selecionar etiquetas",
                    minimumInputLength: 2,
                    language: {
                        inputTooShort: function () {
                            return ""; // Returning empty string to hide the 'input too short' message
                        },
                        noResults: function () {
                            return "Nenhuma etiqueta associada";
                        },
                        searching: function () {
                            return "A procurar..."; // Custom message for searching
                        }
                    },
                    escapeMarkup: function (markup) {
                        return markup;
                    },
                    width: '100%', // Ensures the Select2 input width matches the parent container
                    ajax: {
                        url: '/Folders/GetTags', // Make sure this endpoint returns the data in the correct format
                        dataType: 'json',
                        delay: 250,
                        data: function (params) {
                            return {
                                searchTerm: params.term // Search term
                            };
                        },
                        processResults: function (data) {
                            return {
                                results: data.results
                            };
                        },
                        cache: true
                    }
                }).on("select2:open", function (e) {
                    // Show the select element when Select2 is opened
                    $(this).css('display', 'block');
                });
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>