PlataformaEDUGEP/Models/Folder.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace PlataformaEDUGEP.Models
{
    /// <summary>
    /// Represents a folder within the system, which can contain files and be liked or tagged by users.
    /// </summary>
    public class Folder
    {
        /// <summary>
        /// Gets or sets the primary key for the Folder.
        /// </summary>
        /// <value>
        /// The unique identifier for the folder.
        /// </value>
        [Key]
        public int FolderId { get; set; }

        public string? UserId { get; set; }

        /// <summary>
        /// Gets or sets the name of the folder.
        /// </summary>
        /// <value>
        /// The name of the folder as displayed to the user. Required field.
        /// </value>
        [Required(ErrorMessage = "Por favor, introduza um nome para a pasta.")]
        [Display(Name = "Nome da pasta")]
        public string? Name { get; set; }

        /// <summary>
        /// Gets or sets the user who owns or created the folder.
        /// </summary>
        /// <value>
        /// The user associated with the folder.
        /// </value>
        public ApplicationUser? User { get; set; }

        /// <summary>
        /// Gets or sets the date and time the folder was created.
        /// </summary>
        /// <value>
        /// The creation date and time of the folder.
        /// </value>
        [Display(Name = "Data de criação")]
        public DateTime CreationDate { get; set; }

        /// <summary>
        /// Gets or sets the date and time the folder was last modified.
        /// </summary>
        /// <value>
        /// The last modification date and time of the folder.
        /// </value>
        [Display(Name = "Data de modificação")]
        public DateTime ModificationDate { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the folder is hidden from students.
        /// </summary>
        /// <value>
        /// True if the folder is hidden; otherwise, false.
        /// </value>
        public bool IsHidden { get; set; }

        /// <summary>
        /// Gets or sets the collection of files stored within the folder.
        /// </summary>
        /// <value>
        /// The collection of files.
        /// </value>
        public virtual ICollection<StoredFile> StoredFiles { get; set; } = new List<StoredFile>();

        /// <summary>
        /// Gets or sets the collection of likes associated with the folder.
        /// </summary>
        /// <value>
        /// The collection of likes from different users.
        /// </value>
        public virtual ICollection<FolderLike> Likes { get; set; } = new List<FolderLike>();

        /// <summary>
        /// Gets or sets the collection of tags associated with the folder.
        /// </summary>
        /// <value>
        /// The collection of tags that categorize or describe the folder.
        /// </value>
        public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
    }
}

PlataformaEDUGEP/Controllers/FoldersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Azure.Storage.Blobs;
using PlataformaEDUGEP.Data;
using PlataformaEDUGEP.Models;
using PlataformaEDUGEP.Services;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
using PlataformaEDUGEP.Utilities;

namespace PlataformaEDUGEP.Controllers
{
    /// <summary>
    /// Handles all folder-related interactions within the platform.
    /// </summary>
    public class FoldersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IFolderAuditService _folderAuditService;
        private readonly IWebHostEnvironment _env;
        private readonly BlobServiceClient _blobServiceClient;

        /// <summary>
        /// Constructor for the FoldersController.
        /// </summary>
        /// <param name="context">The application's database context.</param>
        /// <param name="userManager">Manager for handling user-related operations.</param>
        /// <param name="folderAuditService">Service for logging folder-related actions.</param>
        /// <param name="env">Provides information about the web hosting environment.</param>
        /// <param name="blobServiceClient">Client for accessing Azure Blob Storage.</param>
        public FoldersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IFolderAuditService folderAuditService, IWebHostEnvironment env, BlobServiceClient blobServiceClient)
        {
            _context = context;
            _userManager = userManager;
            _folderAuditService = folderAuditService;
            _env = env;
            _blobServiceClient = blobServiceClient;
        }

        /// <summary>
        /// Displays a list of all folders, potentially filtered and sorted.
        /// </summary>
        /// <param name="searchString">Search filter for folder names.</param>
        /// <param name="sortOrder">Sort order for the displayed list.</param>
        /// <param name="selectedTagIds">Filter for folders tagged with specific tags.</param>
        /// <returns>A view of the index page showing folders.</returns>
        [Authorize]
        public async Task<IActionResult> Index(string searchString, string sortOrder, int[] selectedTagIds)
        {
            var userId = _userManager.GetUserId(User);

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.CurrentFilter = searchString;
            ViewBag.SelectedTagIds = selectedTagIds; // Added for tag filtering

            // Ensure Tags SelectList is always passed to the view for the filter dropdown
            ViewBag.AllTags = new SelectList(await _context.Tags.ToListAsync(), "TagId", "Name");

            var folders = _context.Folder.Include(f => f.User).Include(f => f.Tags).AsQueryable();

            if (!User.IsInRole("Teacher") && !User.IsInRole("Admin"))
            {
                folders = folders.Where(f => !f.IsHidden);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                folders = folders.Where(s => s.Name.Contains(searchString));
            }

            // Adjusted Tag filtering logic for AND condition
            if (selectedTagIds != null && selectedTagIds.Length > 0)
            {
                folders = folders.Where(f => f.Tags.Count(t => selectedTagIds.Contains(t.TagId)) == selectedTagIds.Length);
            }

            switch (sortOrder)
            {
                case "name_desc":
                    folders = folders.OrderByDescending(s => s.Name);
                    break;
                case "Date":
                    folders = folders.OrderByDescending(s => s.CreationDate);
                    break;
                case "date_desc":
                    folders = folders.OrderBy(s => s.CreationDate);
                    break;
                default:
                    folders = folders.OrderBy(s => s.Name);
                    break;
            }

            var folderList = await folders.ToListAsync();

            if (!folderList.Any())
            {
                ViewBag.NoResultsFound = "Nenhuma pasta foi encontrada.";
            }

            var likedFolders = await _context.FolderLikes.Where(fl => fl.UserId == userId).Select(fl => fl.FolderId).ToListAsync();
            ViewBag.FolderLikeStatus = folderList.ToDictionary(folder => folder.FolderId, folder => likedFolders.Contains(folder.FolderId));

            return View(folderList);
        }

        /// <summary>
        /// Searches folders by name and returns a JSON list of folders that match the search term.
        /// </summary>
        /// <param name="searchString">The search string to filter folder names.</param>
        /// <returns>A JSON response containing folders that match the search criteria.</returns>
        public async Task<IActionResult> SearchFolders(string searchString)
        {
            var foldersQuery = _context.Folder.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                foldersQuery = foldersQuery.Where(f => f.Name.Contains(searchString));
            }

            var folders = await foldersQuery.Select(f => new { f.FolderId, f.Name }).ToListAsync();

            return Json(folders);
        }

        /// <summary>
        /// Provides a JSON response containing tags that match the given search term.
        /// </summary>
        /// <param name="searchTerm">The search term to filter tags.</param>
        /// <returns>A JSON response with tags matching the search criteria.</returns>
        [HttpGet]
        public async Task<IActionResult> GetTags(string searchTerm)
        {
            var tagsQuery = _context.Tags.AsQueryable();

            if (!string.IsNullOrEmpty(searchTerm))
            {
                tagsQuery = tagsQuery.Where(t => t.Name.Contains(searchTerm));
            }

            var tags = await tagsQuery.Select(tag => new { id = tag.TagId, text = tag.Name }).ToListAsync();

            return Json(new { results = tags });
        }


        /// <summary>
        /// Displays details for a specific folder, including files and associated information.
        /// </summary>
        /// <param name="id">The folder ID for which details are displayed.</param>
        /// <param name="fileTitle">Filter for file titles within the folder.</param>
        /// <param name="addedBy">Filter for files added by specific users.</param>
        /// <param name="sortOrder">Sort order for files within the folder.</param>
        /// <returns>A view displaying folder details.</returns>
        [Authorize]
        public async Task<IActionResult> Details(int? id, string fileTitle, string addedBy, string sortOrder)
        {
            if (id == null)
            {
                return NotFound();
            }

            var folder = await _context.Folder
                .Include(f => f.User)
                .Include(f => f.StoredFiles).ThenInclude(sf => sf.User) // Include User for each StoredFile
                .Include(f => f.Tags) // Include the tags
                .FirstOrDefaultAsync(m => m.FolderId == id);

            if (folder == null)
            {
                return NotFound();
            }

            // Fetch all folders for the dropdown list in the edit modal
            var folders = await _context.Folder.Select(f => new { f.FolderId, f.Name }).ToListAsync();
            ViewBag.FoldersJson = Newtonsoft.Json.JsonConvert.SerializeObject(folders);

            // Apply filters based on search criteria, ensuring case-insensitive comparison
            if (!string.IsNullOrEmpty(fileTitle))
            {
                folder.StoredFiles = folder.StoredFiles
                    .Where(sf => sf.StoredFileTitle.ToLower().Contains(fileTitle.ToLower()))
                    .ToList();
            }
            if (!string.IsNullOrEmpty(addedBy))
            {
                folder.StoredFiles = folder.StoredFiles
                    .Where(sf => sf.User.FullName.ToLower().Contains(addedBy.ToLower()))
                    .ToList();
            }

            // Sorting logic
            switch (sortOrder)
            {
                case "Date":
                    folder.StoredFiles = folder.StoredFiles.OrderBy(sf => sf.UploadDate).ToList();
                    ViewBag.UploadDateSortIcon = "↑";
                    ViewBag.NextSortOrder = "date_desc";
                    break;
                case "date_desc":
                    folder.StoredFiles = folder.StoredFiles.OrderByDescending(sf => sf.UploadDate).ToList();
                    ViewBag.UploadDateSortIcon = "↓";
                    ViewBag.NextSortOrder = "Date";
                    break;
                default:
                    folder.StoredFiles = folder.StoredFiles.OrderByDescending(sf => sf.UploadDate).ToList(); // Default sorting
                    ViewBag.UploadDateSortIcon = "↓";
                    ViewBag.NextSortOrder = "Date";
                    break;
            }

            // Pass the current sorting and filter criteria back to the view via ViewBag
            ViewBag.CurrentSortOrder = sortOrder;
            ViewBag.CurrentFileTitle = fileTitle;
            ViewBag.CurrentAddedBy = addedBy;

            return View(folder);
        }

        /// <summary>
        /// Returns a modal view to create a new folder.
        /// </summary>
        /// <returns>A partial view representing the modal.</returns>
        [Authorize(Roles = "Teacher, Admin")]
        public IActionResult CreateModal()
        {

PlataformaEDUGEP/Controllers/ProfilesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlataformaEDUGEP.Data;
using PlataformaEDUGEP.Models;
using System.Diagnostics;

namespace PlataformaEDUGEP.Controllers
{
    /// <summary>
    /// Manages user profiles within the application, providing methods for CRUD operations and details viewing.
    /// </summary>
    public class ProfilesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        /// <summary>
        /// Initializes a new instance of <see cref="ProfilesController"/> with necessary dependencies.
        /// </summary>
        /// <param name="context">The application's database context.</param>
        /// <param name="userManager">The user manager for handling users.</param>
        public ProfilesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /// <summary>
        /// Displays details for a specific profile.
        /// </summary>
        /// <param name="id">The unique identifier for the profile.</param>
        /// <returns>The details view for the specified profile or Not Found if the profile does not exist.</returns>
        public async Task<IActionResult> Details(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var roles = await _userManager.GetRolesAsync(user);
            var roleLabel = roles.Any(role => role == "Admin") ? "Administrador" :
                            roles.Any(role => role == "Teacher") ? "Professor" :
                            roles.Any(role => role == "Student") ? "Estudante" :
                            "Desconhecido";

            ViewBag.RoleLabel = roleLabel;
            ViewBag.IsStudent = roles.Contains("Student");

            var currentUser = await _userManager.GetUserAsync(User);
            var userRoles = await _userManager.GetRolesAsync(currentUser);
            bool isAdminOrTeacher = userRoles.Contains("Teacher") || userRoles.Contains("Admin");

            var userFolders = await _context.Folder
                .Where(f => f.User.Id == id && (isAdminOrTeacher || !f.IsHidden))
                .ToListAsync();

            ViewBag.UserFolders = userFolders;

            return View(user);
        }

        /// <summary>
        /// Checks if a profile exists in the database.
        /// </summary>
        /// <param name="id">The ID of the profile to check.</param>
        /// <returns>True if the profile exists, false otherwise.</returns>
        private bool ProfileExists(int id)
        {
            return (_context.Profile?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PlataformaEDUGEP/Views/Folders/AuditLog.cshtml
@model IEnumerable<PlataformaEDUGEP.Models.FolderAuditViewModel>

@{
    ViewData["Title"] = "Audit Log";
    int totalPages = (int)ViewData["TotalPages"];
    int currentPage = (int)ViewData["CurrentPage"];
}

<h2>Relatório de ocorrências de pastas</h2>

@{
    var currentFilterUser = ViewData["CurrentFilterUser"]?.ToString();
    var currentFilterAction = ViewData["CurrentFilterAction"]?.ToString();
    var currentFilterFolderName = ViewData["CurrentFilterFolderName"]?.ToString();
    var currentSort = ViewData["CurrentSort"]?.ToString();
}

<form class="my-2 my-lg-0">
    <div class="d-flex flex-row">
        <input class="form-control mr-2" type="search" oninput="updateAuditLog()" placeholder="Utilizador" aria-label="Search User" name="searchUser" value="@currentFilterUser">
        <input class="form-control mr-2" type="search" oninput="updateAuditLog()" placeholder="Tipo de ação" aria-label="Search Action" name="searchAction" value="@currentFilterAction">
        <input class="form-control mr-2" type="search" oninput="updateAuditLog()" placeholder="Nome da Pasta" aria-label="Search Folder Name" name="searchFolderName" value="@currentFilterFolderName">
    </div>
</form>


<div class="mt-2 d-flex align-items-center">
    <button id="clearFiltersButton" onclick="clearFilters()" class="btn btn-secondary mr-2" style="display: none;">Limpar filtros</button>
    <b class="ms-lg-2">Ordenar:</b>

    <!-- Adjust the initial data-sort-order and icon class to match the default sort order -->
    <a href="#" id="sortOrderLink" data-sort-order="time_desc" class="ms-lg-2">
        Hora <i class="fas fa-arrow-down"></i> <!-- Default is desc so show arrow down -->
    </a>


    <form asp-action="ClearAuditLog" asp-controller="Folders" method="post" class="ms-lg-3">
        @Html.AntiForgeryToken()
        <!-- Button to trigger modal -->
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal">
            Resetar registo de ocorrências
        </button>
    </form>

</div>

<div id="audit-log-table">
    @Html.Partial("_AuditLogTablePartial", Model)
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        @for (int i = 1; i <= totalPages; i++)
        {
            <li class="page-item @(i == currentPage ? "active" : "")" onclick="updateAuditLog(null, null, null, null, @i)">
                <span class="page-link">@i</span>
            </li>
        }
    </ul>
</nav>

<!-- Delete Audit Log Modal -->
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteFolderModalLabel">Apagar Registo de Auditoria</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Tem a certeza que deseja apagar todo o registo de ocorrências? Esta ação não pode ser desfeita.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger" onclick="clearAuditLog()">Apagar Tudo</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script>
        // Clears the search filters
        function clearFilters() {
            $("input[name='searchUser']").val('');
            $("input[name='searchAction']").val('');
            $("input[name='searchFolderName']").val('');
            $("#clearFiltersButton").hide(); // Hide the "Limpar filtros" button
            // Reset the audit log without changing the sort order
            updateAuditLog('', '', '', $('#sortOrderLink').data('sort-order'));
        }

        // Updates the visual sort icon based on the sort order
        function updateSortIcon(sortOrder) {
            var iconElement = document.querySelector('#sortOrderLink i');
            iconElement.classList.remove('fa-arrow-up', 'fa-arrow-down');
            iconElement.classList.add(sortOrder === 'time_desc' ? 'fa-arrow-down' : 'fa-arrow-up');
        }

        // Dynamically updates the audit log based on filters, sort order, and page number
        function updateAuditLog(searchUser, searchAction, searchFolderName, sortOrder, pageNumber = 1) {
            // Ensure currentSortOrder is fetched directly if not provided as an argument
            var currentSortOrder = sortOrder || $('#sortOrderLink').data('sort-order');

            $.ajax({
                url: '@Url.Action("AuditLog", "Folders")',
                data: {
                    searchUser: searchUser || $("input[name='searchUser']").val(),
                    searchAction: searchAction || $("input[name='searchAction']").val(),
                    searchFolderName: searchFolderName || $("input[name='searchFolderName']").val(),
                    sortOrder: currentSortOrder,
                    pageNumber: pageNumber, // Pass the pageNumber for pagination
                    pageSize: @ViewData["PageSize"]
                },
                type: 'GET',
                success: function (result) {
                    $('#audit-log-table').html(result);
                    toggleClearFiltersButton();

                    // Update pagination active state
                    updatePaginationActiveState(pageNumber);
                },
                error: function (xhr, status, error) {
                    console.error("Error fetching audit log data: ", status, error);
                }
            });
        }

        // Updates active state on pagination
        function updatePaginationActiveState(activePageNumber) {
            $('.pagination .page-item').removeClass('active'); // Remove active class from all
            $('.pagination .page-item').each(function () {
                if (parseInt($(this).text()) === activePageNumber) {
                    $(this).addClass('active'); // Add active class to the clicked page number
                }
            });
        }

        // Function to handle clear audit log confirmation and action
        function clearAuditLog() {
            if (!confirm('Tem a certeza que deseja apagar todo o registo de auditoria das pastas? Esta ação não pode ser desfeita.')) {
                return;
            }

            $.ajax({
                type: "POST",
                url: '@Url.Action("ClearAuditLog", "Folders")',
                beforeSend: function (xhr) {
                    var token = $('input[name="__RequestVerificationToken"]').val();
                    xhr.setRequestHeader("RequestVerificationToken", token);
                },
                success: function (response) {
                    if (response.success) {
                        alert("Registo de auditoria das pastas apagado com sucesso.");
                        $('#confirmDeleteModal').modal('hide'); // Close the modal dialog
                        // Refresh the audit log section of the page
                        updateAuditLog(); // Call the function to refresh the audit log display

                        // Hide or remove pagination controls
                        $('.pagination').hide(); // or $('.pagination').empty();
                    } else {
                        alert(response.message); // Show the error message from the server
                    }
                },
                error: function (xhr, status, error) {
                    alert("Erro ao apagar o registo de auditoria das pastas: " + error);
                }
            });
        }

        // Toggles the visibility of the "Limpar filtros" button based on input content
        function toggleClearFiltersButton() {
            const hasValue = $("input[name='searchUser']").val() || $("input[name='searchAction']").val() || $("input[name='searchFolderName']").val();
            $("#clearFiltersButton").toggle(!!hasValue);
        }

        $(document).ready(function () {
            // Event handler for sort order change
            $('#sortOrderLink').click(function (e) {
                e.preventDefault();
                var currentSortOrder = $(this).data('sort-order');
                var newSortOrder = currentSortOrder === 'time_desc' ? 'time_asc' : 'time_desc';
                $(this).data('sort-order', newSortOrder);
                updateSortIcon(newSortOrder);
                updateAuditLog(null, null, null, newSortOrder);
            });

            // Bind input change events to toggle the clear filters button
            $("input").on('input', toggleClearFiltersButton);
            toggleClearFiltersButton(); // Ensure correct initial state
        });
    </script>
}

PlataformaEDUGEP/Views/Folders/_AuditLogTablePartial.cshtml
@model IEnumerable<PlataformaEDUGEP.Models.FolderAuditViewModel>

<style>
    .custom-black-border td,
    .custom-black-border th {
        border: 1px solid black;
    }
</style>

<table class="table mt-3 table-bordered custom-black-border">
    <thead class="table-primary">
        <tr>
            <th class="text-center">Utilizador</th>
            <th class="text-center">Tipo de ação realizada</th>
            <th class="text-center">Nome da Pasta</th>
            <th class="text-center">Hora</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var log in Model)
        {
            <tr>
                <td class="text-center">@log.UserName</td>
                <td class="text-center">@log.ActionType</td>
                <td class="text-center">@log.FolderName</td>
                <td class="text-center">@log.ActionTimestamp</td>
            </tr>
        }
    </tbody>
</table>

PlataformaEDUGEP/Views/Folders/_CreatePartial.cshtml
@model PlataformaEDUGEP.Models.Folder

<form asp-action="Create" id="createFolderForm">
    @Html.AntiForgeryToken()

    <div class="form-group mb-3">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" required />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group mb-3">
        <div class="form-check">
        <input asp-for="IsHidden" class="form-check-input" />
        <label asp-for="IsHidden" class="form-check-label">Esconder pasta?</label>
        </div>
    </div>

    <div class="form-group mb-3">
        <label for="tagSelect">Etiquetas</label>
        <select id="tagSelect" asp-items="@(new SelectList(ViewBag.TagItems, "Value", "Text"))" class="form-control select2-tag-select" multiple="multiple" name="SelectedTagIds" style="display: none;"></select>
    </div>

    <div class="center-button">
        <button type="button" class="btn btn-secondary margin-right" data-bs-dismiss="modal">Cancelar</button>
        <input type="submit" value="Criar" class="btn btn-primary" />
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

PlataformaEDUGEP/Views/Folders/_EditPartial.cshtml
@model PlataformaEDUGEP.Models.Folder

<form asp-action="Edit" method="post" id="editFolderForm">
    <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
    <input type="hidden" asp-for="FolderId" />

    <div class="form-group mb-3">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" id="folderName" required />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group mb-3">
        <label asp-for="CreationDate" class="control-label"></label>
        <input asp-for="CreationDate" class="form-control" disabled />
    </div>

    <div class="form-group mb-3">
        <label asp-for="ModificationDate" class="control-label"></label>
        <input asp-for="ModificationDate" class="form-control" disabled />
    </div>

    <div class="form-group mb-3">
        <div class="form-check">
            <input asp-for="IsHidden" class="form-check-input" />
            <label asp-for="IsHidden" class="form-check-label">Esconder pasta?</label>
        </div>
    </div>

    <div class="form-group mb-3">
        <label for="selectedTagIds">Etiquetas</label>
        <select class="form-control select2-tags" id="editTagSelect" name="SelectedTagIds" multiple="multiple" style="display: none;">
            @{
                var selectedTags = ViewBag.SelectedTags as List<int>;
                var tagItems = ViewBag.TagItems as SelectList;
                foreach (var tag in tagItems)
                {
                    bool isSelected = selectedTags != null && selectedTags.Contains(Convert.ToInt32(tag.Value));
                    <!option value="@tag.Value" @(isSelected ? "selected" : "")>@tag.Text</!option>
                }
            }
        </select>
    </div>

    <div class="center-button">
        <button type="button" class="btn btn-secondary margin-right" data-bs-dismiss="modal">Cancelar</button>
        <input type="submit" value="Salvar alterações" class="btn btn-primary" />
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />

}